baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "maddhruv.github.io" # the base hostname & protocol for your site.
title: "Dhruv Jain - @maddhruv"
markdown: kramdown
timezone: Asia/Calcutta

#contacts
git: "https://github.com/maddhruv"
stackoverflow: "http://stackoverflow.com/users/6205689/maddhruv"
twitter: "https://twitter.com/maddhruv"
facebook: "https://facebook.com/maddhruv"
linkedin: "https://www.linkedin.com/in/maddhruv"


gems:
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
