baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "midhruvjaink.github.io" # the base hostname & protocol for your site.
title: "Dhruv Jain - @midhruvjaink"
markdown: kramdown
timezone: Asia/Calcutta

#contacts
git: "https://github.com/midhruvjaink"
stackoverflow: "http://stackoverflow.com/users/6205689/midhruvjaink"
twitter: "https://twitter.com/midhruvjaink"
facebook: "https://facebook.com/midhruvjaink"
linkedin: "https://www.linkedin.com/in/midhruvjaink"


gems:
  - jekyll-paginate

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
